pipeline{

    agent {
    docker {
      image 'abhishekf5/maven-abhishek-docker-agent:v1'
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
    }
  }

    stages {

        stage('Checkout'){
            steps {
              git credentialsId: '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',
              url: 'https://github.com/itzdineshr/example-voting-app',
              branch: 'main'
          }
        }

        stage('Build Docker'){
            environment{
                DOCKER_IMAGE = "dineshr180298/vote-repo:${BUILD_NUMBER}"
            }
            steps{
                script{
                    sh '''
                    echo 'Build Docker Image'
                    cd vote
                    docker build -t ${DOCKER_IMAGE} .
                    '''
                }
            }
        }

        stage('Push Docker Image'){
            steps{
                script{
                    def dockerImage = docker.image("${DOCKER_IMAGE}")
                    docker.withRegistry("https://index.docker.io/v1/","docker-cred"){
                        dockerImage.push()
                    }
                }
            }
        }

    
    }
}