pipeline{

    agent any

    stages {

        stage('Checkout'){
            steps {
              git credentialsId: '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',
              url: 'https://github.com/itzdineshr/example-voting-app',
              branch: 'main'
          }
        }

        stage('Build Docker'){
            environment{
                DOCKER_IMAGE = "dineshr180298/vote-repo:${BUILD_NUMBER}"
            }
            steps{
                script{
                    sh '''
                    echo 'Build Docker Image'
                    cd vote
                    docker build -t ${DOCKER_IMAGE} .
                    '''
                }
            }
        }

        stage('Push Docker Image'){
            environment{
                DOCKER_IMAGE = "dineshr180298/vote-repo:${BUILD_NUMBER}"
            }
            steps{
                script{
                    def dockerImage = docker.image("${DOCKER_IMAGE}")
                    docker.withRegistry("https://index.docker.io/v1/","docker-cred"){
                        dockerImage.push()
                    }
                }
            }
        }

        stage('Update Deployment File'){
            environment{
                GIT_REPO_NAME = "example-voting-app"
                GIT_USER_NAME = "itzdineshr"
                DOCKER_REGISTRY_NAME = "dineshr180298"
                DOCKER_REPO = "vote-repo"
            }
            steps{
                withCredentials([string(credentialsId: 'github_jenkins', variable: 'GITHUB_TOKEN')]){
                    sh '''
                    git config user.email "itzdineshr@gmail.com"
                    git config user.name "Dinesh R"
                    BUILD_NUMBER=${BUILD_NUMBER}
                    sed -i "s|image:.*|image: ${DOCKER_REGISTRY_NAME}/${DOCKER_REPO}:${BUILD_NUMBER}|g" k8s-specifications/vote-deployment.yaml
                    git add k8s-specifications/vote-deployment.yaml
                    git commit -m "Updated deployment image to version ${BUILD_NUMBER}"
                    git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
                    ''' 
                }
            }
        }

    
    }
}